# 使用 browserless/chrome 镜像的简化配置
# 这个配置文件使用现成的 Chrome 服务镜像，无需自己构建

services:
  # Chrome 浏览器服务容器 (使用现成镜像)
  chrome:
    image: browserless/chrome:latest
    ports:
      - "9222:3000"  # browserless 默认端口是 3000
    environment:
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=10
      - ENABLE_DEBUGGER=false
      - PREBOOT_CHROME=true
    restart: unless-stopped
    shm_size: 2gb
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

  # 主应用服务
  feedhub:
    image: fillpit/feedhub:latest
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=production
      - PORT=8009
      - JWT_SECRET=eZjgR0bYm7uEv7uL7tfRMqtaj3lh95OE
      - BASIC_AUTH_USERNAME=admin
      - BASIC_AUTH_PASSWORD=admin@123
      - API_BASE_URL=http://localhost:8008
      - CHROME_SERVICE_URL=http://chrome:3000
    depends_on:
      - chrome
    volumes:
      # 可选：挂载数据目录以持久化数据
      - ./data:/app/backend/data
      - ./logs:/app/backend/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:8008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s