version: '3.8'

services:
  cloud-saver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=production
      - PORT=8009
    volumes:
      # 可选：挂载数据目录以持久化数据
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8008"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 